#:kivy 1.7.2

<Constellation>:
	size_hint: None, None
	pos_hint: {'center_x':.5, 'center_y':.5}

<Star>:
	size_hint: None, None
	size: 18, 18
	pos_hint: {'center_x':self.offset_x, 'center_y':self.offset_y}
	canvas:
		Color:
			rgba: 1, 1, 1, 1
		Ellipse:
			size: self.size
			pos: self.pos

<Connection>:
	canvas:
		Color:
			rgba: 0, 0, .3, 1
		Line:
			width: 8
			points: self.points
		Color:
			rgba: 1, 1, 1, 1
		Line:
			width: 1.2
			points: self.points